name: xbuild
on:
  push:
    branches:
      - main
jobs:
  xbuild:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create tag dry run
        id: tag_version_dry
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: update version file
        run: |
          echo "${{ steps.tag_version_dry.outputs.new_tag }}" > var/version.txt
          cat var/version.txt
      - name: commit & push
        run: |
          git status -sb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update version.txt"
          git push
      - name: cross build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          prefix: zippia
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w -extldflags "-static"
          buildmode: default
          trimpath: true
      - name: chmod & compress
        run: |
          (
            cd build
            for file in `ls`;do
              chmod +x $file
              replaced=`echo $file | sed -E "s/^zippia([^.]+)(.exe)?$/zippia\2/"`
              mv $file $replaced
              zip -r ${file}.zip $replaced
            done;
          )
      - name: create tag and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
